---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
