apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: ingress-nginx-ctrl
  namespace: nginx
spec:
  ports:
  - appProtocol: http
    name: nginx-http
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx-loadbalancer
    app.kubernetes.io/part-of: ingress-nginx
  name: nginx-service-loadbalancer
  namespace: nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: controller

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
